# Generated by Django 3.2.7 on 2022-04-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220408_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
