# Generated by Django 3.2.12 on 2022-05-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_squashed_0029_battlelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='tile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tile',
                to='app.tile',
            ),
        ),
    ]
