# Generated by Django 3.2.12 on 2022-06-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_control_tile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('required_trophies', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Arena',
                'verbose_name_plural': 'Arenas',
                'ordering': ('required_trophies', 'name'),
            },
        ),
    ]
