# Generated by Django 3.2.12 on 2022-06-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_card_warcry_requires_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='creature_type',
            field=models.CharField(
                blank=True,
                choices=[('regular', 'Regular'), ('target', 'Target')],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='card',
            name='creature_targeting_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('only_opponent_creatures', 'Only Opponent Creatures'),
                    ('only_opponent_mysteries', 'Only Opponent Mysteries'),
                    ('only_opponent_spells', 'Only Opponent Spells'),
                    ('only_opponent_all_cards', 'Only Opponent All Cards'),
                    ('only_opponent_avatar', 'Only Opponent Avatar'),
                    ('only_opponent_everything', 'Only Opponent Everything'),
                    ('only_player_creatures', 'Only Player Creatures'),
                    ('only_player_mysteries', 'Only Player Mysteries'),
                    ('only_player_spells', 'Only Player Spells'),
                    ('only_player_all_cards', 'Only Player All Cards'),
                    ('only_player_avatar', 'Only Player Avatar'),
                    ('only_player_everything', 'Only Player Everything'),
                    ('both_player_creatures', 'Both Player Creatures'),
                    ('both_player_mysteries', 'Both Player Mysteries'),
                    ('both_player_spells', 'Both Player Spells'),
                    ('both_player_all_cards', 'Both Player All Cards'),
                    ('both_player_avatars', 'Both Player Avatars'),
                    ('both_player_everything', 'Both Player Everything'),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
