# Generated by Django 3.2.12 on 2022-06-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_change_creature_targeting_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='creature_targeting_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='creature_type',
        ),
    ]
