# Generated by Django 3.2.12 on 2022-06-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_creature_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='spell_type',
            new_name='targeting',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='spell_targeting_type',
            new_name='targeting_type',
        ),
    ]
