# Generated by Django 3.2.12 on 2022-06-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220615_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_arena_name',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='current_experience',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='current_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='current_trophy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='highest_trophy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_season_trophy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlayerActivity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('start_activity', models.DateTimeField()),
                ('end_activity', models.DateTimeField()),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='player_activity_duration',
                        to='app.player',
                    ),
                ),
            ],
        ),
    ]
