# Generated by Django 3.2.12 on 2022-06-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_gamemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(
                blank=True,
                help_text='You can provide keywords, list:<br><br>',
                max_length=512,
                null=True,
            ),
        ),
    ]
