# Generated by Django 3.2.12 on 2022-07-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_gamemode_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(
                blank=True,
                help_text='You can provide keywords, list:<br><br>Last Breath, Warcry, Insult, Barrier, Invisible, Pounce, Ensnare, Ensnared, MIA, Mummy, Untouchable, Apocalype, Censor, Aqua, Dig, Burn, Shock, Mystery, Lethal, Apocalypse, Leech, Censored, Warcries, Mysteries, Water Upgrade, Earth Upgrade, Electricity Upgrade, Fire Upgrade',
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='card',
            name='hp',
            field=models.IntegerField(default=0),
        ),
    ]
