# Generated by Django 3.2.14 on 2022-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_make_card_attack_and_hp_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(
                choices=[
                    ('online', 'Online'),
                    ('offline', 'Offline'),
                    ('away', 'Away'),
                    ('in_battle', 'In battle'),
                ],
                default='offline',
                max_length=50,
            ),
        ),
    ]
