# Generated by Django 3.2.14 on 2022-07-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='game_mode',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='app.gamemode',
            ),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='earn_skill_points_in_this_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='max_cards_in_hand',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='max_tiles_per_player',
            field=models.IntegerField(default=7),
        ),
        migrations.CreateModel(
            name='SkillPointsForBattlePlayer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('skill_points', models.FloatField(default=0)),
                (
                    'battle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_points_for_battle',
                        to='app.battle',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_points_for_player',
                        to='app.player',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='GameModeSeason',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                (
                    'season_reset_multiplier',
                    models.FloatField(
                        default=0,
                        verbose_name='season reset multiplier: how much skill points are kept after season reset (0-1)',
                    ),
                ),
                (
                    'game_mode',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='app.gamemode'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Game Mode Season',
                'verbose_name_plural': 'Game Mode Season',
                'ordering': ('starts_at',),
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='game_mode_season',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='app.gamemodeseason',
            ),
        ),
    ]
