# Generated by Django 3.2.14 on 2022-07-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_game_modes_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='card_death_count',
            field=models.IntegerField(default=0),
        ),
    ]
