# Generated by Django 3.2.14 on 2022-07-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_tile_card_death_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardhand',
            name='card_death_count',
            field=models.IntegerField(default=0),
        ),
    ]
