# Generated by Django 3.2.14 on 2022-07-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220719_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPointsLadder',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('level', models.IntegerField(default=1)),
                ('skill_points_required', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0)),
                (
                    'game_mode',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='app.gamemode'
                    ),
                ),
            ],
            options={
                'ordering': ('level',),
            },
        ),
    ]
