# Generated by Django 3.2.14 on 2022-07-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_unused_game_mode_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('skill_points', models.IntegerField(default=0)),
                ('skill_level', models.IntegerField(default=0)),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='player_to_season',
                        to='app.player',
                    ),
                ),
                (
                    'season',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='season_to_player',
                        to='app.gamemodeseason',
                    ),
                ),
            ],
        ),
    ]
