# Generated by Django 3.2.14 on 2022-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_playerseasonstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstats',
            name='season_highest',
            field=models.IntegerField(default=0),
        ),
    ]
