# Generated by Django 3.2.14 on 2022-07-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_playerseasonstats_season_highest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillPointsForBattlePlayer',
        ),
    ]
