# Generated by Django 3.2.14 on 2022-07-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_delete_skillpointsforbattleplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPointsForBattlePlayer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('skill_points', models.FloatField(default=0)),
                (
                    'battle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_points_for_battle',
                        to='app.battle',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_points_for_player',
                        to='app.player',
                    ),
                ),
            ],
        ),
    ]
