# Generated by Django 3.2.14 on 2022-07-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_caching_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardactivemystery',
            name='remove_last_breath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carddeck',
            name='remove_last_breath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardgraveyard',
            name='remove_last_breath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardhand',
            name='remove_last_breath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='control',
            name='remove_last_breath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tile',
            name='remove_last_breath',
            field=models.BooleanField(default=False),
        ),
    ]
