# Generated by Django 3.2.14 on 2022-07-26 12:59

import app.models.battle
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_add_remove_last_breath_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLogMongo',
            fields=[
                (
                    'id',
                    models.CharField(
                        default=app.models.battle.generate_random_id,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('battle_id', models.TextField(db_index=True)),
                ('battle_player_id', models.TextField()),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('client_event', 'client_event'),
                            ('server_event', 'server_event'),
                        ],
                        default='client_event',
                        max_length=32,
                    ),
                ),
                ('event_json', djongo.models.fields.JSONField()),
            ],
            options={
                'verbose_name': 'Battle Log',
                'verbose_name_plural': 'Battle Logs',
                'ordering': ('timestamp',),
                'managed': False,
                'in_db': 'nonrel',
            },
        ),
    ]
