# Generated by Django 3.2.14 on 2022-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_battlelogmongo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enchantment',
            name='protect',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enchantment',
            name='keyword',
            field=models.CharField(choices=[('warcry', 'Warcry'), ('censor', 'Censor'), ('leech', 'Leech'), ('insult', 'Insult'), ('pounce', 'Pounce'), ('barrier', 'Barrier'), ('untouchable', 'Untouchable'), ('mummy', 'Mummy'), ('ensnare', 'Ensnare'), ('mia', 'MIA'), ('tile_buff', 'Tile Buff'), ('protect', 'Protect')], default='warcry', max_length=100),
        ),
    ]
