# Generated by Django 3.2.14 on 2022-08-02 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_protected_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='original_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_to_tile_original', to='app.card'),
        ),
    ]
