# Generated by Django 3.2.14 on 2022-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_activeplayersovertime_playersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstats',
            name='skill_level',
            field=models.IntegerField(default=1),
        ),
    ]
