# Generated by Django 3.2.14 on 2022-08-11 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_skillpointsladder_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='current_turn_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.player'),
        ),
    ]
