# Generated by Django 3.2.14 on 2022-08-14 14:56

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    Battle = apps.get_model('app', 'Battle')
    Battle.objects.update(current_turn_player_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_enchantment_keyword'),
    ]

    operations = [
        migrations.RunPython(code=forward, reverse_code=forward),
        migrations.AlterField(
            model_name='battle',
            name='current_turn_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_battle', to='app.battleplayer'),
        ),
    ]
