# Generated by Django 3.2.15 on 2022-08-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_battle_current_turn_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='body',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
