# Generated by Django 3.2.15 on 2022-08-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_player_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstats',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
    ]
