# Generated by Django 3.2.15 on 2022-08-16 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_playerseasonstats_xp_earned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.CharField(max_length=16)),
                ('is_currently_selected', models.BooleanField(default=False, verbose_name='True if this version is selected. Use actions to modify in admin.')),
            ],
            options={
                'verbose_name': 'Client Version',
                'verbose_name_plural': 'Client Versions',
                'ordering': ('-created_at',),
            },
        ),
    ]
