# Generated by Django 3.2.15 on 2022-08-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_friendship_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardactivemystery',
            name='battle_card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carddeck',
            name='battle_card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardgraveyard',
            name='battle_card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardhand',
            name='battle_card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='battle_card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='battle_card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
