# Generated by Django 3.2.15 on 2022-08-31 17:11

from django.db import migrations, models

def add_record_to_table(apps, schema_editor):
    Onboarding = apps.get_model('app', 'Onboarding')

    Onboarding.objects.create(
        data={}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_battle_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(add_record_to_table),
    ]
