# Generated by Django 3.2.15 on 2022-09-01 14:49

import app.models.analytics_info
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsInfo',
            fields=[
                ('id', models.CharField(default=app.models.analytics_info.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(max_length=120)),
                ('event_json', djongo.models.fields.JSONField()),
            ],
            options={
                'ordering': ('-created_at',),
                'managed': False,
                'in_db': 'nonrel',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='add_all_nft_cards',
            field=models.BooleanField(default=False),
        ),
    ]
