# Generated by Django 3.2.15 on 2022-09-05 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_player_add_nft_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='enchantment',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enchantments', to='app.battleplayer'),
        ),
    ]
