# Generated by Django 3.2.15 on 2022-09-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20220912_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='error',
            field=models.CharField(max_length=2000),
        ),
    ]
