# Generated by Django 3.2.15 on 2022-09-15 09:15

from django.db import migrations, models


def migrate_old_fields(apps, schema_editor):
    Card = apps.get_model('app', 'Card')
    Card.objects.filter(targeting_type__in=[
        'only_opponent_mysteries',
        'only_opponent_spells',
        'only_opponent_all_cards',
    ]).update(targeting_type='only_opponent_creatures')
    Card.objects.filter(targeting_type__in=[
        'only_player_mysteries',
        'only_player_spells',
        'only_player_all_cards',
    ]).update(targeting_type='only_player_creatures')
    Card.objects.filter(targeting_type__in=[
        'both_player_mysteries',
        'both_player_spells',
        'both_player_all_cards',
    ]).update(targeting_type='both_player_creatures')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20220912_1830'),
    ]

    operations = [
        migrations.RunPython(migrate_old_fields),
        migrations.AlterField(
            model_name='card',
            name='targeting_type',
            field=models.CharField(blank=True, choices=[('only_opponent_tiles', 'Only Opponent Tiles'), ('only_opponent_creatures', 'Only Opponent Creatures'), ('only_opponent_avatar', 'Only Opponent Avatar'), ('only_opponent_everything', 'Only Opponent Everything'), ('only_player_tiles', 'Only Player Tiles'), ('only_player_creatures', 'Only Player Creatures'), ('only_player_avatar', 'Only Player Avatar'), ('only_player_everything', 'Only Player Everything'), ('both_player_tiles', 'Both Player Tiles'), ('both_player_creatures', 'Both Player Creatures'), ('both_player_avatars', 'Both Player Avatars'), ('both_player_everything', 'Both Player Everything')], max_length=64, null=True),
        ),
    ]
