# Generated by Django 3.2.15 on 2022-09-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_card_targeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='is_graveyard_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='is_random_generated_deck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='max_cards_in_deck',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='show_next_card_from_deck',
            field=models.BooleanField(default=False),
        ),
    ]
