# Generated by Django 3.2.15 on 2022-09-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_gamemode_start_cards_on_hand_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='start_battle_player_hp',
            field=models.IntegerField(default=30),
        ),
    ]
