# Generated by Django 3.2.15 on 2022-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_gamemode_start_battle_player_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_gitex_bear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_gitex_bull',
            field=models.BooleanField(default=False),
        ),
    ]
