# Generated by Django 3.2.15 on 2022-09-28 16:02
from django.db import migrations

from app.card_abilities import cards as cards_module


def available_cards(apps, schema_editor):
    Card = apps.get_model('app', 'Card')
    card_names = (card for card in dir(cards_module) if not card.startswith('_'))
    Card.objects.filter(custom_id__in=card_names).update(is_enabled=True)


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0060_add_player_gitex_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='is_published',
            new_name='is_enabled',
        ),
        migrations.RunPython(available_cards),
    ]
