# Generated by Django 3.2.15 on 2022-10-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_rename_is_published_card_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='deal_damage_to_avatar_on_empty_deck',
            field=models.BooleanField(default=True),
        ),
    ]
