# Generated by Django 3.2.15 on 2022-10-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20221007_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardactivemystery',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='carddeck',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='cardgraveyard',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='cardhand',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='tile',
            options={'ordering': ('order',)},
        ),
    ]
