# Generated by Django 3.2.15 on 2022-10-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_gamemode_battle_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFTGenerator',
        ),
    ]
